vault_unseal_keys_encrypted: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32366633373363363830646132643237333039613030386530393337326533363835356432653363
          6130383862626232326133386561666237323331303834650a666462393438363266346436666432
          36366339366632366436363463643336626165663134653234643636613234623536626330393533
          6539633832663434630a306565333237326130396266623564623061656265656534346161383866
          35366135353838313365656334316664333138323766333763323230613965666530356132373564
          37376361633164623966623237633038373431393635626565656430653863663738343339653338
          64346535616132626532323463366364356362613338633334383363396133303961653631316239
          31653639336630373730393430623539363038393066306634643337376261663238356234326535
          65303533643436636165376239623265323230366362326430356331333365313433383535623936
          36656361373763386533373365373139643139323631323437656639616266626631373532363336
          33323962613637663761396661646534643036663364316131626637633465323337313330353239
          30353935396230383066346333666638656335333061666430393964396330646165613337306636
          30363263306634636634363238326163313465386264363237396231373366373064353332663662
          63663566366531303861643731633535313033306330366532323865363363313063613931656262
          38326439653535623933643536613562646537383564303836613635356561633433303534346535
          36616262623462366666623062666133626561303432633962363733653438333530613531643561
          65653635613263653930613438306332343836393830363636356339643830656132656265616665
          66646132343538356335366434356165643665343937313164363731343362363266343238356338
          63663762666431323337353862646534383737356661313736313632643561303430366230656630
          31353537363765663864636432646434623863313032306232313739396366616363663938633430
          30316535663665303663623636336638613762306233356633643730656133613733613430396564
          38396466313936323939383035616436353537643461653636636264356466323233383839363431
          30656365366563613738383230333865373630346138366362343336356435326436343132663361
          33613730313130666662343735613830373364313961326633646461656430616438313536653064
          31646136323766666666626533646137663065666430633131393863363865376131306536356330
          64393334643234393566383632373736353038346335393731626431613165346563623238363061
          38306233666536636566303166633532346337393538323764323861643033643336333437626430
          34363064636231303765303536393435353866653733393633626336643230396532653062303066
          36323565653337363631333433386234633436633566363936393730393637386635633532666465
          63363961353637346666336263396638653163636463393664313139666534386139636162663432
          38306430363665666535303064386663303330656131306138303035623936323334366533363934
          37326338613761313332303339376461313032613834303835303266333131383234343830616238
          31303438636364383439323433633734613835343065336639336430626130393163383739643239
          34656637393531326261303661623932313931303432363530303137343935323933303539653665
          64333334663463653863623435376661623337636435613332373062626636353439666338653731
          34616266343931326430383435663635396164626338306134633832616266396637376530323764
          39356266643963363735616639373939633961653538393435666138313239666366383765316530
          33323566376530653839633433323139343433353435386162376336373039343335326530336539
          64343761393361313963363763376365303336316262636565393035653862313062343238366666
          63363332616436313164663831373839373334333936343439633838343739346531393866376339
          63353262623339386239393130376534633336636236353765613865653366373539613765323030
          35383937396538653335343830353736373564653630383532656136633731323330353538646662
          65326262656435303632633834613463363234383433393162653332353563346466343734313163
          62363234396338396436373239376164313031313334356662353830643938383766666164373237
          39663231363932303539363830373066616461353961326262313532343338646431666532633561
          66636261313662373236353735333530386130326365656137646430323632663936363536393133
          39626434393363633836383139366565643431316264336339353363363931663534653238636662
          37366635633435323661386137386235333031356636373861336437373631353632323733323566
          32353635623337393937313436653239316663396665353832626235646466333662