---
- name: Setup ESXi hosts
  hosts: vsphere
  gather_facts: false
  become: false
  roles:
    - name: Build custom esxi iso (optional)
      role: manage_esxi
      vars:
        mes_build_iso: True
      tags:
        - never
        - create_iso
    - name: Install OS via iso mount
      role: redfish
      tags:
        - redfish
