---
- name: Setup ESXi hosts
  hosts: vsphere
  gather_facts: false
  become: false
  roles:
    - name: Build custom esxi iso (optional)
      role: lit.supplementary.manage_esxi
      vars:
        manage_esxi_build_iso: true
      tags:
        - never
        - create_iso
    - name: Install OS via iso mount
      role: lit.supplementary.redfish
      tags:
        - redfish
