---
- name: Configure ESXi hosts via vCenter
  hosts: vsphere_esxi
  gather_facts: False
  become: False
  roles:
    - name: Execute role manage_esxi
      role: manage_esxi
      tags:
        - manage_esxi
