---
- name: Microsoft Active Directory Setup
  hosts: dc
  gather_facts: True
  roles:
    - name: Execute role active_directory
      role: active_directory
      tags:
        - active_directory
...
