---
- name: Setup gitlab omnibus
  hosts: gitlab_runner_omnibus
   
  gather_facts: True
  roles:
    - name: Execute role gitlab_runner_omnibus
      role: gitlab_runner_omnibus
      tags:
        - gitlab_runner_omnibus
...
