---
keycloak_env: "dev"
keycloak_api_url: "https://kc.example.int"
keycloak_realm: "platform"

keycloak_clients:
  - id: "gitlab"
    name: "GitLab"
    redirect_uris:
      - "https://gitlab.example.int/users/auth/openid_connect/callback"
  - id: "ocp"
    name: "OpenShift"
    redirect_uris:
      - "https://oauth-openshift.apps.ocp.example.int/oauth2callback"
