---
collections:
  - name: community.vmware
  - name: community.hashi_vault
    version: ">=7.1.0"
  - name: lit.supplementary
    version: ">=1.3.0"
  - name: lit.foundational
    version: ">=1.3.0"

