---
collections:
  - name: ansible.posix
    version: "2.1.0"
  - name: community.vmware
  - name: community.hashi_vault
    version: ">=7.1.0"
  - name: fedora.linux_system_roles
    version: "1.120.3"
  - name: lit.supplementary
    version: ">=1.3.0"
  - name: lit.foundational
    version: ">=1.3.0"
  - name: lit.rhel
    version: ">=1.4.3"
  - name: ansible.hub
    version: "1.0.0"
  - name: ansible.controller
    version: "4.6.16"
  - name: ansible.eda
    version: "2.8.1"
  - name: ansible.platform
    version: "2.5.20250702"
  - name: community.general
    version: "11.1.0"
  - name: community.crypto
    version: "2.26.3"
  - name: containers.podman
    version: "1.17.0"
  - name: infra.aap_utilities
    version: "2.7.0"
  - name: infra.aap_configuration
    version: "3.4.1"
  - name: infra.aap_configuration_extended
    version: "1.1.1"
  - name: infra.controller_configuration
    version: "3.1.2"
  - name: infra.ee_utilities
    version: "4.0.4"
  - name: redhat.satellite
    version: "5.4.0"
