---
collections:
  - name: ansible.posix
  - name: community.vmware
  - name: community.hashi_vault
    version: ">=7.1.0"
  - name: fedora.linux_system_roles
    version: "1.120.2"
  - name: lit.supplementary
    version: ">=1.3.0"
  - name: lit.foundational
    version: ">=1.3.0"
  - name: lit.rhel
    version: ">=1.4.3"
