---
# Overrides for production in the commercial zone
vcenter_datacenter: CHANGEME_DATACENTER
vcenter_cluster: CHANGEME_CLUSTER
vcenter_folder: CHANGEME_FOLDER
network_name: CHANGEME_COM_PRD_NET
vlan_id: CHANGEME_VLAN

vmware_vsphere_vmware_guest_cluster: cluster-01
vmware_vsphere_datacenter: DC1
vmware_vsphere_vmware_iso_datastore: "datastore-hyp01-01"
vmware_vsphere_network: sn-admin-com-mgmt-admin01-171
vmware_vsphere_folder_name: /{{ vmware_vsphere_datacenter }}/vm
