---
# vCenter
manage_esxi_vcenter_hostname: vcenter01-com.mgmt.corp.l-it.io
manage_esxi_vcenter_username: administrator@vsphere.local
manage_esxi_vcenter_password: TET&jekOB75e

# ESXi hyp01
manage_esxi_username: root
manage_esxi_initial_password: install2023!
manage_esxi_password: sqNULry4c!9fBve
manage_esxi_hostname: hyp01.core.corp.l-it.io
manage_esxi_hostname_ext: hyp01.core.cloud.l-it.io
manage_esxi_domainame: core.cloud.l-it.io
manage_esxi_dns_servers:
  - 10.10.30.3
  - 185.12.64.2
manage_esxi_search_domains:
    - l-it.io
    - core.cloud.l-it.io
manage_esxi_datacenter_name: dc-lit
manage_esxi_cluster_name: cluster-01
manage_esxi_license: 4F01H-0RK40-H80N9-A13NK-0Y2N0

# ESXi general
manage_esxi_options: 
  Config.HostAgent.log.level: verbose
  Annotations.WelcomeMessage: Lightning IT - VMware ESXi - {{ manage_esxi_hostname }}
  Config.HostAgent.plugins.solo.enableMob: true
  UserVars.SuppressShellWarning: 1

manage_esxi_portgroups:
  Management Network EXT:
    portgroup: Management Network EXT
    switch: vSwitch0
    vlan_id: 0
  Management Network INT:
    portgroup: Management Network INT
    switch: vSwitch0
    vlan_id: 4051
  sn-wl-com-prd-core01-561:
    portgroup: sn-wl-com-prd-core01-561
    switch: vSwitch0
    vlan_id: 561
  sn-admin-com-mgmt-admin01-171:
    portgroup: sn-admin-com-mgmt-admin01-171
    switch: vSwitch0
    vlan_id: 171
  sn-wl-dmz-prd-edge01-1771:
    portgroup: sn-wl-dmz-prd-edge01-1771
    switch: vSwitch0
    vlan_id: 1771
  sn-mgmt-dmz-prd-host01-1391:
    portgroup: sn-mgmt-dmz-prd-host01-1391
    switch: vSwitch0
    vlan_id: 1391

allowd_ip_adress:
  - 116.202.254.243
  - 116.202.254.244
  - 80.152.174.182
  - 93.241.78.196

allowd_ip_network:
  - 10.10.30.0/24
  - 172.16.30.0/24
